import 'dart:async';

import 'package:http/http.dart' as http;

/// Manages NTP time offset to prevent device-clock spoofing.
/// Calculates the delta between the true network time and the local device
/// clock. When offline, the previously computed offset stored in RAM is applied
/// to all timestamps generated by the app.
class NtpService {
  NtpService._();
  static final instance = NtpService._();

  Duration _offset = Duration.zero;
  bool _initialized = false;

  Duration get offset => _offset;
  bool get isInitialized => _initialized;

  /// The corrected "true" time: device clock + NTP offset.
  DateTime get now => DateTime.now().toUtc().add(_offset);

  /// Synchronize with an NTP-like HTTP time source.
  /// Uses Google's cached time endpoint as a lightweight fallback
  /// since the pure NTP package has platform-level socket issues.
  Future<void> synchronize() async {
    try {
      final beforeRequest = DateTime.now().toUtc();

      final response = await http
          .head(Uri.parse('https://www.google.com'))
          .timeout(const Duration(seconds: 5));

      final afterRequest = DateTime.now().toUtc();
      final dateHeader = response.headers['date'];
      if (dateHeader == null) return;

      final serverTime = _parseHttpDate(dateHeader);
      if (serverTime == null) return;

      final roundTrip = afterRequest.difference(beforeRequest);
      final estimatedServerTime = serverTime.add(roundTrip ~/ 2);
      final midPoint = beforeRequest.add(roundTrip ~/ 2);

      _offset = estimatedServerTime.difference(midPoint);
      _initialized = true;
    } catch (_) {
      // Offline or timeout — keep existing offset (zero if first boot)
    }
  }

  static DateTime? _parseHttpDate(String dateStr) {
    try {
      return DateTime.parse(dateStr);
    } catch (_) {
      // HTTP-date format: "Tue, 24 Mar 2026 12:00:00 GMT"
      try {
        return _parseRfc1123(dateStr);
      } catch (_) {
        return null;
      }
    }
  }

  static DateTime? _parseRfc1123(String dateStr) {
    const months = {
      'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
      'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12,
    };

    final parts = dateStr.replaceAll(',', '').split(RegExp(r'\s+'));
    if (parts.length < 5) return null;

    final day = int.tryParse(parts[1]);
    final month = months[parts[2]];
    final year = int.tryParse(parts[3]);
    final timeParts = parts[4].split(':');

    if (day == null || month == null || year == null || timeParts.length < 3) {
      return null;
    }

    return DateTime.utc(
      year, month, day,
      int.parse(timeParts[0]),
      int.parse(timeParts[1]),
      int.parse(timeParts[2]),
    );
  }
}
