-- ============================================================================
-- @migration PipelineEventsLog
-- @status COMPLETE
-- @description SUPERSEDED — merged into 042_pipeline_resilience.sql (no-op)
-- @tables (none — no-op)
-- @lastAudit 2026-03-22
-- ============================================================================

-- No-op: all statements from the original 042_pipeline_events_log.sql have been
-- merged into 042_pipeline_resilience.sql with idempotent (IF NOT EXISTS /
-- CREATE OR REPLACE) guards. Running this file is safe but does nothing.
